name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Lintly-Flake8
      uses: grantmcconnaughey/lintly-flake8-github-action@v1.0

    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
