name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install Python requirements
      uses: aabadie/action-install-python-requirements@v2.0.1
    - name: lint code
      run: | 
        flake8 --ignore=E501,E231 *.py 
        

    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
